# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: devolo/idl/proto/deviceapi/restart.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='devolo/idl/proto/deviceapi/restart.proto',
  package='device.api',
  syntax='proto3',
  serialized_options=_b('\n\006deviceB\007restart'),
  serialized_pb=_b('\n(devolo/idl/proto/deviceapi/restart.proto\x12\ndevice.api\"\x80\x01\n\x0fRestartResponse\x12\x32\n\x06result\x18\x01 \x01(\x0e\x32\".device.api.RestartResponse.Result\x12\x0e\n\x06uptime\x18\x02 \x01(\x03\")\n\x06Result\x12\x0b\n\x07SUCCESS\x10\x00\x12\x12\n\rUNKNOWN_ERROR\x10\xff\x01\"#\n\x11UptimeGetResponse\x12\x0e\n\x06uptime\x18\x02 \x01(\x03\x42\x11\n\x06\x64\x65viceB\x07restartb\x06proto3')
)



_RESTARTRESPONSE_RESULT = _descriptor.EnumDescriptor(
  name='Result',
  full_name='device.api.RestartResponse.Result',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_ERROR', index=1, number=255,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=144,
  serialized_end=185,
)
_sym_db.RegisterEnumDescriptor(_RESTARTRESPONSE_RESULT)


_RESTARTRESPONSE = _descriptor.Descriptor(
  name='RestartResponse',
  full_name='device.api.RestartResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='device.api.RestartResponse.result', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uptime', full_name='device.api.RestartResponse.uptime', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RESTARTRESPONSE_RESULT,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=185,
)


_UPTIMEGETRESPONSE = _descriptor.Descriptor(
  name='UptimeGetResponse',
  full_name='device.api.UptimeGetResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uptime', full_name='device.api.UptimeGetResponse.uptime', index=0,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=187,
  serialized_end=222,
)

_RESTARTRESPONSE.fields_by_name['result'].enum_type = _RESTARTRESPONSE_RESULT
_RESTARTRESPONSE_RESULT.containing_type = _RESTARTRESPONSE
DESCRIPTOR.message_types_by_name['RestartResponse'] = _RESTARTRESPONSE
DESCRIPTOR.message_types_by_name['UptimeGetResponse'] = _UPTIMEGETRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RestartResponse = _reflection.GeneratedProtocolMessageType('RestartResponse', (_message.Message,), dict(
  DESCRIPTOR = _RESTARTRESPONSE,
  __module__ = 'devolo.idl.proto.deviceapi.restart_pb2'
  # @@protoc_insertion_point(class_scope:device.api.RestartResponse)
  ))
_sym_db.RegisterMessage(RestartResponse)

UptimeGetResponse = _reflection.GeneratedProtocolMessageType('UptimeGetResponse', (_message.Message,), dict(
  DESCRIPTOR = _UPTIMEGETRESPONSE,
  __module__ = 'devolo.idl.proto.deviceapi.restart_pb2'
  # @@protoc_insertion_point(class_scope:device.api.UptimeGetResponse)
  ))
_sym_db.RegisterMessage(UptimeGetResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
