"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _WifiResult:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _WifiResultEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_WifiResult.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    WIFI_SUCCESS: _WifiResult.ValueType  # 0
    WIFI_INVALID_SSID: _WifiResult.ValueType  # 1
    WIFI_INVALID_KEY: _WifiResult.ValueType  # 2
    WIFI_IS_DISABLED: _WifiResult.ValueType  # 3
    WIFI_UNKNOWN_ERROR: _WifiResult.ValueType  # 255
class WifiResult(_WifiResult, metaclass=_WifiResultEnumTypeWrapper):
    pass

WIFI_SUCCESS: WifiResult.ValueType  # 0
WIFI_INVALID_SSID: WifiResult.ValueType  # 1
WIFI_INVALID_KEY: WifiResult.ValueType  # 2
WIFI_IS_DISABLED: WifiResult.ValueType  # 3
WIFI_UNKNOWN_ERROR: WifiResult.ValueType  # 255
global___WifiResult = WifiResult


class _WifiBand:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _WifiBandEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_WifiBand.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    WIFI_BAND_UNKNOWN: _WifiBand.ValueType  # 0
    WIFI_BAND_2G: _WifiBand.ValueType  # 1
    WIFI_BAND_5G: _WifiBand.ValueType  # 2
class WifiBand(_WifiBand, metaclass=_WifiBandEnumTypeWrapper):
    pass

WIFI_BAND_UNKNOWN: WifiBand.ValueType  # 0
WIFI_BAND_2G: WifiBand.ValueType  # 1
WIFI_BAND_5G: WifiBand.ValueType  # 2
global___WifiBand = WifiBand


class _WifiVAPType:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _WifiVAPTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_WifiVAPType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    WIFI_VAP_UNKNOWN: _WifiVAPType.ValueType  # 0
    WIFI_VAP_MAIN_AP: _WifiVAPType.ValueType  # 1
    WIFI_VAP_GUEST_AP: _WifiVAPType.ValueType  # 2
    WIFI_VAP_STATION: _WifiVAPType.ValueType  # 3
class WifiVAPType(_WifiVAPType, metaclass=_WifiVAPTypeEnumTypeWrapper):
    pass

WIFI_VAP_UNKNOWN: WifiVAPType.ValueType  # 0
WIFI_VAP_MAIN_AP: WifiVAPType.ValueType  # 1
WIFI_VAP_GUEST_AP: WifiVAPType.ValueType  # 2
WIFI_VAP_STATION: WifiVAPType.ValueType  # 3
global___WifiVAPType = WifiVAPType


class WifiParametersSet(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SSID_FIELD_NUMBER: builtins.int
    KEY_FIELD_NUMBER: builtins.int
    ssid: typing.Text
    """WiFi ssid"""

    key: typing.Text
    """WiFi key, independent of the type (WPA2, ...)"""

    def __init__(self,
        *,
        ssid: typing.Text = ...,
        key: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["key",b"key","ssid",b"ssid"]) -> None: ...
global___WifiParametersSet = WifiParametersSet

class WifiParametersSetResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    RESULT_FIELD_NUMBER: builtins.int
    result: global___WifiResult.ValueType
    """contains the result of setting WiFi Parameter message"""

    def __init__(self,
        *,
        result: global___WifiResult.ValueType = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["result",b"result"]) -> None: ...
global___WifiParametersSetResponse = WifiParametersSetResponse

class WifiGuestAccessSet(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ENABLE_FIELD_NUMBER: builtins.int
    DURATION_FIELD_NUMBER: builtins.int
    enable: builtins.bool
    duration: builtins.int
    """time in minutes; 0 is infinity"""

    def __init__(self,
        *,
        enable: builtins.bool = ...,
        duration: builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["duration",b"duration","enable",b"enable"]) -> None: ...
global___WifiGuestAccessSet = WifiGuestAccessSet

class WifiGuestAccessSetResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    RESULT_FIELD_NUMBER: builtins.int
    result: global___WifiResult.ValueType
    """contains the result of setting WiFi Guest Access parameters"""

    def __init__(self,
        *,
        result: global___WifiResult.ValueType = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["result",b"result"]) -> None: ...
global___WifiGuestAccessSetResponse = WifiGuestAccessSetResponse

class WifiGuestAccessGet(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ENABLED_FIELD_NUMBER: builtins.int
    REMAINING_DURATION_FIELD_NUMBER: builtins.int
    SSID_FIELD_NUMBER: builtins.int
    KEY_FIELD_NUMBER: builtins.int
    enabled: builtins.bool
    remaining_duration: builtins.int
    ssid: typing.Text
    key: typing.Text
    def __init__(self,
        *,
        enabled: builtins.bool = ...,
        remaining_duration: builtins.int = ...,
        ssid: typing.Text = ...,
        key: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["enabled",b"enabled","key",b"key","remaining_duration",b"remaining_duration","ssid",b"ssid"]) -> None: ...
global___WifiGuestAccessGet = WifiGuestAccessGet

class WifiNeighborAPsGet(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class NeighborAPInfo(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        MAC_ADDRESS_FIELD_NUMBER: builtins.int
        SSID_FIELD_NUMBER: builtins.int
        BAND_FIELD_NUMBER: builtins.int
        CHANNEL_FIELD_NUMBER: builtins.int
        SIGNAL_FIELD_NUMBER: builtins.int
        SIGNAL_BARS_FIELD_NUMBER: builtins.int
        mac_address: typing.Text
        ssid: typing.Text
        band: global___WifiBand.ValueType
        channel: builtins.int
        signal: builtins.int
        signal_bars: builtins.int
        def __init__(self,
            *,
            mac_address: typing.Text = ...,
            ssid: typing.Text = ...,
            band: global___WifiBand.ValueType = ...,
            channel: builtins.int = ...,
            signal: builtins.int = ...,
            signal_bars: builtins.int = ...,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["band",b"band","channel",b"channel","mac_address",b"mac_address","signal",b"signal","signal_bars",b"signal_bars","ssid",b"ssid"]) -> None: ...

    NEIGHBOR_APS_FIELD_NUMBER: builtins.int
    @property
    def neighbor_aps(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___WifiNeighborAPsGet.NeighborAPInfo]: ...
    def __init__(self,
        *,
        neighbor_aps: typing.Optional[typing.Iterable[global___WifiNeighborAPsGet.NeighborAPInfo]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["neighbor_aps",b"neighbor_aps"]) -> None: ...
global___WifiNeighborAPsGet = WifiNeighborAPsGet

class WifiRepeatedAPsGet(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class RepeatedAPInfo(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        MAC_ADDRESS_FIELD_NUMBER: builtins.int
        SSID_FIELD_NUMBER: builtins.int
        BAND_FIELD_NUMBER: builtins.int
        CHANNEL_FIELD_NUMBER: builtins.int
        RATE_FIELD_NUMBER: builtins.int
        SIGNAL_FIELD_NUMBER: builtins.int
        SIGNAL_BARS_FIELD_NUMBER: builtins.int
        mac_address: typing.Text
        ssid: typing.Text
        band: global___WifiBand.ValueType
        channel: builtins.int
        rate: builtins.int
        signal: builtins.int
        signal_bars: builtins.int
        def __init__(self,
            *,
            mac_address: typing.Text = ...,
            ssid: typing.Text = ...,
            band: global___WifiBand.ValueType = ...,
            channel: builtins.int = ...,
            rate: builtins.int = ...,
            signal: builtins.int = ...,
            signal_bars: builtins.int = ...,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["band",b"band","channel",b"channel","mac_address",b"mac_address","rate",b"rate","signal",b"signal","signal_bars",b"signal_bars","ssid",b"ssid"]) -> None: ...

    REPEATED_APS_FIELD_NUMBER: builtins.int
    @property
    def repeated_aps(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___WifiRepeatedAPsGet.RepeatedAPInfo]: ...
    def __init__(self,
        *,
        repeated_aps: typing.Optional[typing.Iterable[global___WifiRepeatedAPsGet.RepeatedAPInfo]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["repeated_aps",b"repeated_aps"]) -> None: ...
global___WifiRepeatedAPsGet = WifiRepeatedAPsGet

class WifiConnectedStationsGet(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class ConnectedStationInfo(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        MAC_ADDRESS_FIELD_NUMBER: builtins.int
        VAP_TYPE_FIELD_NUMBER: builtins.int
        BAND_FIELD_NUMBER: builtins.int
        RX_RATE_FIELD_NUMBER: builtins.int
        TX_RATE_FIELD_NUMBER: builtins.int
        mac_address: typing.Text
        vap_type: global___WifiVAPType.ValueType
        band: global___WifiBand.ValueType
        rx_rate: builtins.int
        tx_rate: builtins.int
        def __init__(self,
            *,
            mac_address: typing.Text = ...,
            vap_type: global___WifiVAPType.ValueType = ...,
            band: global___WifiBand.ValueType = ...,
            rx_rate: builtins.int = ...,
            tx_rate: builtins.int = ...,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["band",b"band","mac_address",b"mac_address","rx_rate",b"rx_rate","tx_rate",b"tx_rate","vap_type",b"vap_type"]) -> None: ...

    CONNECTED_STATIONS_FIELD_NUMBER: builtins.int
    @property
    def connected_stations(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___WifiConnectedStationsGet.ConnectedStationInfo]: ...
    def __init__(self,
        *,
        connected_stations: typing.Optional[typing.Iterable[global___WifiConnectedStationsGet.ConnectedStationInfo]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["connected_stations",b"connected_stations"]) -> None: ...
global___WifiConnectedStationsGet = WifiConnectedStationsGet

class WifiRepeaterParametersSet(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SSID_FIELD_NUMBER: builtins.int
    KEY_FIELD_NUMBER: builtins.int
    CROSSBAND_FIELD_NUMBER: builtins.int
    PRIMARY_BAND_FIELD_NUMBER: builtins.int
    ssid: typing.Text
    """Wifi ssid"""

    key: typing.Text
    """Wifi key, independent of the type (WPA2, ...)"""

    crossband: builtins.bool
    """Use crossband (true) or in-band repeating (false)"""

    primary_band: global___WifiBand.ValueType
    """Primary backhaul band when using crossband"""

    def __init__(self,
        *,
        ssid: typing.Text = ...,
        key: typing.Text = ...,
        crossband: builtins.bool = ...,
        primary_band: global___WifiBand.ValueType = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["crossband",b"crossband","key",b"key","primary_band",b"primary_band","ssid",b"ssid"]) -> None: ...
global___WifiRepeaterParametersSet = WifiRepeaterParametersSet

class WifiRepeaterParametersSetResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    RESULT_FIELD_NUMBER: builtins.int
    result: global___WifiResult.ValueType
    def __init__(self,
        *,
        result: global___WifiResult.ValueType = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["result",b"result"]) -> None: ...
global___WifiRepeaterParametersSetResponse = WifiRepeaterParametersSetResponse

class WifiWpsPbcStart(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    RESULT_FIELD_NUMBER: builtins.int
    result: global___WifiResult.ValueType
    def __init__(self,
        *,
        result: global___WifiResult.ValueType = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["result",b"result"]) -> None: ...
global___WifiWpsPbcStart = WifiWpsPbcStart

class WifiRepeaterWpsClonePbcStart(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    RESULT_FIELD_NUMBER: builtins.int
    result: global___WifiResult.ValueType
    def __init__(self,
        *,
        result: global___WifiResult.ValueType = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["result",b"result"]) -> None: ...
global___WifiRepeaterWpsClonePbcStart = WifiRepeaterWpsClonePbcStart
