"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class IdentifyDeviceStart(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    MAC_ADDRESS_FIELD_NUMBER: builtins.int
    mac_address: typing.Text
    """MAC address of the targeted device"""

    def __init__(self,
        *,
        mac_address: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["mac_address",b"mac_address"]) -> None: ...
global___IdentifyDeviceStart = IdentifyDeviceStart

class IdentifyDeviceStop(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    MAC_ADDRESS_FIELD_NUMBER: builtins.int
    mac_address: typing.Text
    """MAC address of the targeted device"""

    def __init__(self,
        *,
        mac_address: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["mac_address",b"mac_address"]) -> None: ...
global___IdentifyDeviceStop = IdentifyDeviceStop

class IdentifyDeviceResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class _Result:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType
    class _ResultEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[IdentifyDeviceResponse._Result.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        SUCCESS: IdentifyDeviceResponse._Result.ValueType  # 0
        MACADDR_INVALID: IdentifyDeviceResponse._Result.ValueType  # 1
        MACADDR_UNKNOWN: IdentifyDeviceResponse._Result.ValueType  # 2
        COMMUNICATION_ERROR: IdentifyDeviceResponse._Result.ValueType  # 254
        UNKNOWN_ERROR: IdentifyDeviceResponse._Result.ValueType  # 255
    class Result(_Result, metaclass=_ResultEnumTypeWrapper):
        pass

    SUCCESS: IdentifyDeviceResponse.Result.ValueType  # 0
    MACADDR_INVALID: IdentifyDeviceResponse.Result.ValueType  # 1
    MACADDR_UNKNOWN: IdentifyDeviceResponse.Result.ValueType  # 2
    COMMUNICATION_ERROR: IdentifyDeviceResponse.Result.ValueType  # 254
    UNKNOWN_ERROR: IdentifyDeviceResponse.Result.ValueType  # 255

    RESULT_FIELD_NUMBER: builtins.int
    result: global___IdentifyDeviceResponse.Result.ValueType
    """contains the result of StartIdentifyDevice and StopIdentifyDevice message"""

    def __init__(self,
        *,
        result: global___IdentifyDeviceResponse.Result.ValueType = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["result",b"result"]) -> None: ...
global___IdentifyDeviceResponse = IdentifyDeviceResponse
